# Generated by Django 5.0.14 on 2026-08-31 00:00
# Hand-authored to match the autodetector's own output shape (no venv with
# the pinned Django 5.0.x + full app dependency set available in this
# environment to run `makemigrations` directly) — see
# specs/002-recovery-towing-web-portal/data-model.md.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
