# Generated by Django 5.0.14 on 2026-08-19 15:26

import django.contrib.gis.db.models.fields
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Explicit: PointField's autodetector doesn't infer this, but
        # postgis must exist before a geometry column can be created —
        # see apps/common/migrations/0001_enable_postgis_extension.py.
        ('common', '0001_enable_postgis_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(default=False)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=3)),
                ('vehicle_plate', models.CharField(blank=True, max_length=30, null=True)),
                ('service_radius_km', models.PositiveIntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'provider_profiles',
            },
        ),
    ]
